# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-deployment
#   namespace: devops-app
# spec:
#   replicas: 2 # Luon chay 2 may de du phong
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: bingsu1103/devops-backend:latest
#           ports:
#             - containerPort: 7070
#           env:
#             - name: SPRING_DATASOURCE_URL
#               value: "jdbc:postgresql://YOUR_RDS_ENDPOINT:5432/dev_inventory_db"
#             - name: SPRING_DATASOURCE_USERNAME
#               value: "dbadmin"
#             - name: SPRING_DATASOURCE_PASSWORD
#               value: "REPLACE_WITH_ACTUAL_DB_PASSWORD" # Nen dung K8s Secret nhung demo dung env cho de hieu
#             - name: SPRING_DATASOURCE_DRIVER
#               value: "org.postgresql.Driver"
#             - name: SPRING_JPA_HIBERNATE_DDL_AUTO
#               value: "update"
