# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   namespace: devops-app
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 7070 # Thay doi tu 80 -> 7070 cho dong bo
#       targetPort: 7070
#   type: ClusterIP # Chi truy cap ben trong cluster hoac qua Ingress
