BACKEND_PORT=7070
FRONTEND_PORT=3000
DOCKER_USER=bingsu1103
AWS_SSH_KEY_NAME=AWS_key_pair
DOMAIN_NAME=
FRONTEND_DOMAIN_NAME=edulearnlms.online
BACKEND_DOMAIN_NAME=api.edulearnlms.online
SSL_ENABLED=true
CERTBOT_EMAIL=ngogiaan11111@gmail.com