spring.application.name=devops-pipeline

# Datasource Configuration (Cho phép ghi đè từ Prod)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:exampledb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server
server.port=7070

# Mở endpoint /actuator/prometheus cho Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
# Hiển thị chi tiết health check
management.endpoint.health.show-details=always
# Thêm tag tên ứng dụng cho các biểu đồ
management.metrics.tags.application=${spring.application.name}
