pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'prod'], description: 'Select the environment to deploy')
        string(name: 'BACKEND_PORT', defaultValue: '', description: 'Enter Port for the Backend service (Required)')
        string(name: 'FRONTEND_PORT', defaultValue: '', description: 'Enter Port for the Frontend service (Required)')

        string(name: 'DOCKERHUB_USER_PARAM', defaultValue: '', description: 'Enter your Docker Hub Username (Required)')
    }


    environment {
        PATH = "/opt/homebrew/bin:/usr/local/bin:${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'dockerhub-creds'
        DOCKER_USER = "${params.DOCKERHUB_USER_PARAM}"
        TAG = "build-${env.BUILD_NUMBER}"
    }

    stages {
        stage('Validate Parameters') {
            steps {
                script {
                    if (params.DOCKERHUB_USER_PARAM == "" || params.BACKEND_PORT == "" || params.FRONTEND_PORT == "") {
                        error "DOCKERHUB_USER_PARAM, BACKEND_PORT and FRONTEND_PORT are required! Please provide them when building."
                    }

                }
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Artifacts') {
            steps {
                dir('backend') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Infrastructure Provisioning') {
            steps {
                withCredentials([
                    string(credentialsId: 'aws-access-key', variable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'aws-secret-key', variable: 'AWS_SECRET_ACCESS_KEY'),
                    string(credentialsId: 'rds-db-password', variable: 'DB_PASS')
                ]) {
                    dir("infrastructure/envs/${params.ENVIRONMENT}") {
                        sh 'terraform init'
                        sh "terraform apply -var='db_password=${env.DB_PASS}' -var='backend_port=${params.BACKEND_PORT}' -var='frontend_port=${params.FRONTEND_PORT}' -auto-approve"
                        
                        script {
                            // Extract IP from Terraform Output
                            def backend_ip = sh(script: "terraform output -raw backend_public_ip", returnStdout: true).trim()
                            def frontend_ip = sh(script: "terraform output -raw frontend_public_ip", returnStdout: true).trim()
                            def rds_endpoint_full = sh(script: "terraform output -raw rds_endpoint", returnStdout: true).trim()
                            def rds_host = rds_endpoint_full.split(":")[0]

                            env.BACKEND_IP = backend_ip
                            env.FRONTEND_IP = frontend_ip
                            env.RDS_HOST = rds_host

                            echo "Current Deployment IP - Backend: ${env.BACKEND_IP}, Frontend: ${env.FRONTEND_IP}"

                            // Generate Ansible inventory from template
                            def inventoryTplPath = "${env.WORKSPACE}/ansible/inventory/${params.ENVIRONMENT}.ini.example"
                            def inventoryTpl = readFile(inventoryTplPath)
                            def activeInventory = inventoryTpl
                                .replace("{{ BACKEND_IP }}", env.BACKEND_IP)
                                .replace("{{ FRONTEND_IP }}", env.FRONTEND_IP)
                                .replace("{{ RDS_HOST }}", env.RDS_HOST)
                                .replace("{{ DB_PASS }}", env.DB_PASS)
                            
                            writeFile(file: "${env.WORKSPACE}/ansible/inventory/${params.ENVIRONMENT}.ini", text: activeInventory)
                        }
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    sh "chmod +x ci-cd/scripts/*.sh"
                    withEnv([
                        "NEXT_PUBLIC_API_URL=http://${env.BACKEND_IP}:${params.BACKEND_PORT}",
                        "DOCKERHUB_USER=${env.DOCKER_USER}"
                    ]) {
                        sh "./ci-cd/scripts/build.sh ${TAG}"
                    }
                }
            }
        }

        stage('Push DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS_ID}", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "docker login -u ${USER} -p ${PASS}"
                        withEnv(["DOCKERHUB_USER=${env.DOCKER_USER}"]) {
                            sh "./ci-cd/scripts/push.sh ${TAG}"
                        }
                    }
                }
            }
        }

        stage('Configuration & Deploy') {
            steps {
                    sshagent(['ec2-ssh-key']) {
                        dir('ansible') {
                            sh "ansible-playbook -i inventory/${params.ENVIRONMENT}.ini playbooks/setup.yml"
                            sh "ansible-playbook -i inventory/${params.ENVIRONMENT}.ini playbooks/deploy.yml --extra-vars 'image_tag=${TAG} docker_user=${env.DOCKER_USER} backend_port=${params.BACKEND_PORT} frontend_port=${params.FRONTEND_PORT}'"

                        }
                    }
            }
        }
    }

    post {
        always {
            echo "--- Pipeline for ${params.ENVIRONMENT} environment completed ---"
        }
    }
}

